alias l='ls -F --group-directories-first --color=auto'
alias ll='l -Flh --group-directories-first --color=auto'
alias lll='l -Flha --group-directories-first --color=auto'
alias install-basics='apt install mc vim htop iotop ncdu fdupes locales-all'
alias install-venv='python3 -m venv .venv'
alias whatismyip='curl ipinfo.io/ip; echo'
